/*
 * File: TheViewport.ui.js
 * Date: Mon Oct 18 2010 15:14:28 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

TheViewportUi = Ext.extend(Ext.Viewport, {
    layout: 'border',
    id: 'viewport',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                region: 'center',
                id: 'center_panel'
            },
            {
                xtype: 'panel',
                title: 'Navigation',
                region: 'west',
                width: 175,
                minWidth: 100,
                boxMaxWidth: 250,
                collapsible: true,
                padding: '12px',
                items: [
                    {
                        xtype: 'treepanel',
                        rootVisible: false,
                        border: false,
                        root: {
                            text: 'Root',
                            children: [
                                {
                                    text: 'Projects',
                                    children: [
                                        {
                                            text: 'View Dashboard',
                                            leaf: true
                                        }
                                    ]
                                },
                                {
                                    text: 'Work In Progress',
                                    children: [
                                        {
                                            text: 'All WIP Reports',
                                            leaf: true
                                        },
                                        {
                                            text: 'Your WIP Items',
                                            leaf: true
                                        }
                                    ]
                                },
                                {
                                    text: 'Rota',
                                    children: [
                                        {
                                            text: 'All Rotas',
                                            leaf: true
                                        },
                                        {
                                            text: 'Your Rota',
                                            leaf: true
                                        },
                                        {
                                            text: 'Your Teams Rota',
                                            leaf: true
                                        }
                                    ]
                                },
                                {
                                    text: 'Documentation',
                                    children: [
                                        {
                                            text: 'Help Files',
                                            leaf: true
                                        },
                                        {
                                            text: 'Bugs/Code',
                                            leaf: true
                                        }
                                    ]
                                },
                                {
                                    text: 'Your Account',
                                    children: [
                                        {
                                            text: 'Logout',
                                            leaf: true
                                        }
                                    ]
                                }
                            ]
                        },
                        loader: {

                        }
                    }
                ]
            }
        ];
        TheViewportUi.superclass.initComponent.call(this);
    }
});
