/*
 * File: TheViewport.js
 * Date: Fri Oct 15 2010 19:27:19 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

TheViewport = Ext.extend(TheViewportUi, {
    initComponent: function() {
        TheViewport.superclass.initComponent.call(this);
    }
});
