/*
 * File: StoreRiskCounterMeasure.js
 * Date: Thu Oct 21 2010 16:06:58 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

StoreRiskCounterMeasure = Ext.extend(Ext.data.ArrayStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        StoreRiskCounterMeasure.superclass.constructor.call(this, Ext.apply({
            storeId: 'st_counter',
            data: [
                [
                    1,
                    "Prevention"
                ],
                [
                    2,
                    "Acceptance"
                ],
                [
                    3,
                    "Transfer"
                ],
                [
                    4,
                    "Reduction"
                ],
                [
                    5,
                    "Contingency"
                ]
            ],
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'data'
                }
            ]
        }, cfg));
    }
});
new StoreRiskCounterMeasure();