/*
 * File: MyPanel.ui.js
 * Date: Thu Oct 21 2010 17:31:20 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyPanelUi = Ext.extend(Ext.Panel, {
    title: 'Project Management',
    id: 'panel_project_mgmt',
    initComponent: function() {
        this.items = [
            {
                xtype: 'toolbar',
                id: 'tb_project_toolbar',
                items: [
                    {
                        xtype: 'button',
                        text: 'Add',
                        id: 'btn_add_items',
                        menu: {
                            xtype: 'menu',
                            id: 'menu_add_items',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Add Company'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Add Project',
                                    id: 'menu_add_project'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Add Skillset'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'button',
                        text: 'Manage',
                        id: 'btn_manage_project',
                        menu: {
                            xtype: 'menu',
                            id: 'menu_manage_project',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Add Deliverable',
                                    id: 'menu_add_deliverable'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Add Risk',
                                    id: 'menu_add_risk'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Add Issue'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Add Lesson Learnt'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Add Report'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Add Work Item',
                                    id: 'menu_add_wbs'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Add File'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Edit Project Initiation'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'button',
                        text: 'View',
                        id: 'btn_view_project',
                        menu: {
                            xtype: 'menu',
                            id: 'menu_view_project',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'View Project Timeline'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'View Gantt Chart'
                                }
                            ]
                        }
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                activeTab: 3,
                height: 462,
                padding: '15px',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Project Initiation'
                    },
                    {
                        xtype: 'panel',
                        title: 'Deliverables',
                        items: [
                            {
                                xtype: 'panel',
                                layout: 'border',
                                height: 400,
                                id: 'panel_deliverables',
                                items: [
                                    {
                                        xtype: 'grid',
                                        store: 'st_deliverables',
                                        region: 'west',
                                        split: true,
                                        width: 868,
                                        id: 'grid_deliverables',
                                        tbar: {
                                            xtype: 'toolbar',
                                            id: 'tbar_grid_deliverables',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Add Deliverable',
                                                    iconCls: 'icon-add',
                                                    id: 'btn_add_deliverable'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Update Deliverable',
                                                    iconCls: 'icon-update',
                                                    id: 'btn_update_deliverable'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Delete Deliverable',
                                                    iconCls: 'icon-complete',
                                                    id: 'btn_delete_deliverable'
                                                }
                                            ]
                                        },
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'description',
                                                header: 'Description',
                                                sortable: true,
                                                width: 100
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'acceptance_criteria',
                                                header: 'Acceptance Criteria',
                                                sortable: true,
                                                width: 100,
                                                align: 'right',
                                                hidden: true
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'deliverable_tester',
                                                header: 'Deliverable Tester',
                                                sortable: true,
                                                width: 100
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'testing_method',
                                                header: 'Testing Method',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'expected_result',
                                                header: 'Expected Result',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'rto',
                                                header: 'RTO',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'rpo',
                                                header: 'RPO',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'created_date',
                                                header: 'Created Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'modified_date',
                                                header: 'Modified Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        region: 'center',
                                        html: 'Please select an object to see more details',
                                        padding: '12px',
                                        id: 'panel_deliverables_detail'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Risks',
                        items: [
                            {
                                xtype: 'panel',
                                layout: 'border',
                                height: 400,
                                id: 'panel_risks',
                                items: [
                                    {
                                        xtype: 'grid',
                                        store: 'st_risks',
                                        region: 'west',
                                        split: true,
                                        width: 868,
                                        id: 'grid_risks',
                                        tbar: {
                                            xtype: 'toolbar',
                                            id: 'tbar_grid_risks',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Add Risk',
                                                    id: 'btn_add_risk'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Update Risk'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Delete Risk'
                                                }
                                            ]
                                        },
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'risk_number',
                                                header: 'Risk Number',
                                                sortable: true,
                                                width: 100
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'description',
                                                header: 'Description',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'probability',
                                                header: 'Probability',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'impact',
                                                header: 'Impact',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'rating',
                                                header: 'Rating',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'created_date',
                                                header: 'Created Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'modified_date',
                                                header: 'Modified Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        region: 'center',
                                        html: 'Please select an object to see more details',
                                        padding: '12px',
                                        id: 'panel_risks_detail'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Work Items',
                        items: [
                            {
                                xtype: 'panel',
                                layout: 'border',
                                height: 400,
                                id: 'panel_wbs',
                                items: [
                                    {
                                        xtype: 'grid',
                                        store: 'st_wbs',
                                        region: 'west',
                                        split: true,
                                        width: 868,
                                        id: 'grid_wbs',
                                        tbar: {
                                            xtype: 'toolbar',
                                            id: 'tbar_grid_wbs',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Add Project Stage'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Add Work Item',
                                                    id: 'btn_add_wbs'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Update Work Item'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Delete Work Item'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Add Engineering Day'
                                                }
                                            ]
                                        },
                                        columns: [
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'wbs_number',
                                                header: 'WBS Number',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'skill_set',
                                                header: 'Skillset',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'stage',
                                                header: 'Stage',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'author',
                                                header: 'Author',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'title',
                                                header: 'Title',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'description',
                                                header: 'Description',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'duration',
                                                header: 'Duration',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'owner',
                                                header: 'Owner',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'percent_complete',
                                                header: 'Percent Complete',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'start_date',
                                                header: 'Start Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'finish_date',
                                                header: 'Finish Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'work_status',
                                                header: 'Work Status',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'cost',
                                                header: 'Cost',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'created_date',
                                                header: 'Created Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'modified_date',
                                                header: 'Modified Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        region: 'center',
                                        html: 'Please select an object to see more details',
                                        padding: '12px',
                                        id: 'panel_wbs_detail'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Issues',
                        items: [
                            {
                                xtype: 'panel',
                                layout: 'border',
                                height: 400,
                                id: 'panel_issues',
                                items: [
                                    {
                                        xtype: 'grid',
                                        store: 'st_risks',
                                        region: 'west',
                                        split: true,
                                        width: 868,
                                        id: 'grid_issues',
                                        tbar: {
                                            xtype: 'toolbar',
                                            id: 'tbar_grid_issues',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Add Issue'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Update Issue'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Delete Issue'
                                                }
                                            ]
                                        },
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'description',
                                                header: 'Description',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'owner',
                                                header: 'Owner',
                                                sortable: true,
                                                width: 100
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'author',
                                                header: 'Author',
                                                sortable: true,
                                                width: 100
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'status',
                                                header: 'Status',
                                                sortable: true,
                                                width: 100
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'type',
                                                header: 'Type',
                                                sortable: true,
                                                width: 100
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'priority',
                                                header: 'Priority',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'created_date',
                                                header: 'Created Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'modified_date',
                                                header: 'Modified Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        region: 'center',
                                        html: 'Please select an object to see more details',
                                        padding: '12px',
                                        id: 'panel_issues_detail'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Lessons Learnt',
                        items: [
                            {
                                xtype: 'panel',
                                layout: 'border',
                                height: 400,
                                id: 'panel_lessons',
                                items: [
                                    {
                                        xtype: 'grid',
                                        store: 'st_risks',
                                        region: 'west',
                                        split: true,
                                        width: 868,
                                        id: 'grid_lessons',
                                        tbar: {
                                            xtype: 'toolbar',
                                            id: 'tbar_grid_lessons',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Add Lesson'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Update Lesson'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Delete Lesson'
                                                }
                                            ]
                                        },
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'description',
                                                header: 'Description',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'author',
                                                header: 'Author',
                                                sortable: true,
                                                width: 100
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'created_date',
                                                header: 'Created Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'modified_date',
                                                header: 'Modified Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        region: 'center',
                                        html: 'Please select an object to see more details',
                                        padding: '12px',
                                        id: 'panel_lessons_detail'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Reports',
                        items: [
                            {
                                xtype: 'panel',
                                layout: 'border',
                                height: 400,
                                id: 'panel_reports',
                                items: [
                                    {
                                        xtype: 'grid',
                                        store: 'st_risks',
                                        region: 'west',
                                        split: true,
                                        width: 868,
                                        id: 'grid_reports',
                                        tbar: {
                                            xtype: 'toolbar',
                                            id: 'tbar_grid_reports',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Add Report'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Update Report'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Delete Report'
                                                }
                                            ]
                                        },
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'author',
                                                header: 'Author',
                                                sortable: true,
                                                width: 100
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'type',
                                                header: 'Type',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'summary',
                                                header: 'Summary',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'created_date',
                                                header: 'Created Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'modified_date',
                                                header: 'Modified Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        region: 'center',
                                        html: 'Please select an object to see more details',
                                        padding: '12px',
                                        id: 'panel_reports_detail'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Files',
                        items: [
                            {
                                xtype: 'panel',
                                layout: 'border',
                                height: 400,
                                id: 'panel_files',
                                items: [
                                    {
                                        xtype: 'grid',
                                        store: 'st_risks',
                                        region: 'west',
                                        split: true,
                                        width: 868,
                                        id: 'grid_files',
                                        tbar: {
                                            xtype: 'toolbar',
                                            id: 'tbar_grid_files',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Add File'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Update File'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Delete File'
                                                }
                                            ]
                                        },
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'description',
                                                header: 'Description',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'file_type',
                                                header: 'File Type',
                                                sortable: true,
                                                width: 100,
                                                align: 'right'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'author',
                                                header: 'Author',
                                                sortable: true,
                                                width: 100
                                            },
                                            {
                                                xtype: 'datecolumn',
                                                dataIndex: 'created_date',
                                                header: 'Created Date',
                                                sortable: true,
                                                width: 100,
                                                hidden: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        region: 'center',
                                        html: 'Please select an object to see more details',
                                        padding: '12px',
                                        id: 'panel_files_detail'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ];
        MyPanelUi.superclass.initComponent.call(this);
    }
});
