/*
 * File: StoreDeliverables.js
 * Date: Thu Oct 21 2010 17:31:20 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

StoreDeliverables = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        StoreDeliverables.superclass.constructor.call(this, Ext.apply({
            storeId: 'st_deliverables',
            root: 'data',
            url: '',
            fields: [
                {
                    name: 'description',
                    mapping: 'description'
                },
                {
                    name: 'id',
                    mapping: 'id'
                },
                {
                    name: 'acceptance_criteria',
                    mapping: 'acceptance_criteria'
                },
                {
                    name: 'deliverable_tester',
                    mapping: 'deliverable_tester'
                },
                {
                    name: 'testing_method',
                    mapping: 'testing_method'
                },
                {
                    name: 'expected_result',
                    mapping: 'expected_result'
                },
                {
                    name: 'rpo',
                    mapping: 'rpo'
                },
                {
                    name: 'rto',
                    mapping: 'rto'
                },
                {
                    name: 'created_date',
                    mapping: 'created_date',
                    type: 'date'
                },
                {
                    name: 'modified_date',
                    mapping: 'modified_date',
                    type: 'date'
                }
            ]
        }, cfg));
    }
});
new StoreDeliverables();