/*
 * File: StoreProjectStage.js
 * Date: Thu Oct 21 2010 17:45:15 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

StoreProjectStage = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        StoreProjectStage.superclass.constructor.call(this, Ext.apply({
            storeId: 'st_stage_plan',
            fields: [
                {
                    name: 'id',
                    mapping: 'id'
                },
                {
                    name: 'stage',
                    mapping: 'stage'
                },
                {
                    name: 'description',
                    mapping: 'description'
                },
                {
                    name: 'stage_number',
                    mapping: 'stage_number'
                }
            ]
        }, cfg));
    }
});
new StoreProjectStage();