/*
 * File: xds_index.js
 * Date: Mon Oct 18 2010 15:14:28 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new TheViewport({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
