/*
 * File: MyPanel.js
 * Date: Fri Oct 15 2010 20:20:25 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

MyPanel = Ext.extend(MyPanelUi, {
    initComponent: function() {
        MyPanel.superclass.initComponent.call(this);
    }
});
Ext.reg('mypanel', MyPanel);