/*
 * File: StoreRisks.js
 * Date: Thu Oct 21 2010 17:31:20 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

StoreRisks = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        StoreRisks.superclass.constructor.call(this, Ext.apply({
            storeId: 'st_risks',
            root: 'data',
            fields: [
                {
                    name: 'id',
                    mapping: 'id'
                },
                {
                    name: 'risk_number',
                    mapping: 'risk_number'
                },
                {
                    name: 'description',
                    mapping: 'description'
                },
                {
                    name: 'owner',
                    mapping: 'owner'
                },
                {
                    name: 'probability',
                    mapping: 'probability'
                },
                {
                    name: 'impact',
                    mapping: 'impact'
                },
                {
                    name: 'rating',
                    mapping: 'rating'
                },
                {
                    name: 'history',
                    mapping: 'history'
                },
                {
                    name: 'history_html',
                    mapping: 'history_html'
                },
                {
                    name: 'counter_measure',
                    mapping: 'counter_measure'
                },
                {
                    name: 'status',
                    mapping: 'status'
                },
                {
                    name: 'created_date',
                    mapping: 'created_date',
                    type: 'date'
                },
                {
                    name: 'modified_date',
                    mapping: 'modified_date',
                    type: 'date'
                }
            ]
        }, cfg));
    }
});
new StoreRisks();