/*
 * File: WindowAddWBS.ui.js
 * Date: Thu Oct 21 2010 17:45:15 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

WindowAddWBSUi = Ext.extend(Ext.Window, {
    title: 'Add / Edit Work Item',
    width: 568,
    height: 561,
    modal: true,
    id: 'window_add_wbs',
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                padding: '15px',
                id: 'form_add_wbs',
                items: [
                    {
                        xtype: 'combo',
                        fieldLabel: 'Skillset',
                        anchor: '100%',
                        name: 'skillset',
                        triggerAction: 'all',
                        mode: 'local',
                        store: 'st_skillset'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Title',
                        anchor: '100%',
                        name: 'title'
                    },
                    {
                        xtype: 'combo',
                        fieldLabel: 'Project Stage',
                        anchor: '100%',
                        name: 'project_stage',
                        triggerAction: 'all',
                        mode: 'local',
                        store: 'st_stage_plan'
                    },
                    {
                        xtype: 'combo',
                        fieldLabel: 'Depends Upon',
                        anchor: '100%',
                        name: 'depends',
                        triggerAction: 'all',
                        mode: 'local',
                        store: 'st_wbs'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Duration',
                        anchor: '100%',
                        name: 'duration'
                    },
                    {
                        xtype: 'textarea',
                        anchor: '100%',
                        fieldLabel: 'Description',
                        name: 'description'
                    },
                    {
                        xtype: 'combo',
                        fieldLabel: 'Owner',
                        anchor: '100%',
                        name: 'owner',
                        triggerAction: 'all',
                        mode: 'local',
                        store: 'st_resources'
                    },
                    {
                        xtype: 'sliderfield',
                        value: 40,
                        fieldLabel: 'Percent Complete',
                        anchor: '100%',
                        name: 'percent_complete'
                    },
                    {
                        xtype: 'datefield',
                        fieldLabel: 'Start Date',
                        anchor: '100%',
                        name: 'start_date'
                    },
                    {
                        xtype: 'datefield',
                        fieldLabel: 'Finish Date',
                        anchor: '100%',
                        name: 'finish_date'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Cost',
                        anchor: '100%',
                        itemId: 'cost'
                    },
                    {
                        xtype: 'textarea',
                        fieldLabel: 'Update',
                        anchor: '100%',
                        name: 'update'
                    },
                    {
                        xtype: 'textarea',
                        fieldLabel: 'History',
                        anchor: '100%',
                        name: 'history',
                        readOnly: true
                    }
                ]
            }
        ];
        WindowAddWBSUi.superclass.initComponent.call(this);
    }
});
