/*
 * File: WindowAddWBS.js
 * Date: Thu Oct 21 2010 17:37:45 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

WindowAddWBS = Ext.extend(WindowAddWBSUi, {
    initComponent: function() {
        WindowAddWBS.superclass.initComponent.call(this);
    }
});
