/*
 * File: WindowAddRisk.js
 * Date: Thu Oct 21 2010 14:53:30 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

WindowAddRisk = Ext.extend(WindowAddRiskUi, {
    initComponent: function() {
        WindowAddRisk.superclass.initComponent.call(this);
    }
});
