/*
 * File: WindowAddDeliverable.js
 * Date: Mon Oct 18 2010 16:31:38 GMT+0100 (BST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

WindowAddDeliverable = Ext.extend(WindowAddDeliverableUi, {
    initComponent: function() {
        WindowAddDeliverable.superclass.initComponent.call(this);
    }
});
